import { NextResponse } from "next/server";
import { generateMockLaunchKit } from "@/lib/generate";
import { callLLM, getActiveProvider, LLMRouterError } from "@/lib/llm/router";
import { buildLaunchKitMessages } from "@/lib/llm/promptLaunchKit";
import { parseLaunchKit, LaunchKitParseError } from "@/lib/llm/parseLaunchKit";
import type { ConceptInput } from "@/lib/types";

// Launch kit generation does a lot of writing (10 tweets, 20 raid replies,
// 5 DM templates, telegram, dexscreener copy, 7-day plan). 30s+ on grok-4
// is normal — bump the function timeout off the 10s default.
export const maxDuration = 60;
export const runtime = "nodejs";

// ─────────────────────────────────────────────────────────────────────────
// POST /api/generate-launch-kit
//
// Behavior (transparent by design):
//   • If XAI_API_KEY is set (recommended) → calls xAI Grok.
//   • Otherwise tries Anthropic → OpenAI in order.
//   • If no key is configured OR all providers fail → returns mock kit
//     and tells the client (`mock: true`, `fallbackReason`).
//
// The response always echoes which provider/model actually served the
// request so the UI can show "Generated by Grok / Claude / Mock" — we
// never claim a model that didn't run.
//
// Hard rule: this server NEVER signs anything. It only prepares drafts.
// ─────────────────────────────────────────────────────────────────────────

export async function POST(req: Request) {
  let body: Partial<ConceptInput> = {};
  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { ok: false, error: "Invalid JSON body" },
      { status: 400 }
    );
  }

  const required = ["idea", "tokenName", "ticker"] as const;
  for (const k of required) {
    if (!body[k] || String(body[k]).trim() === "") {
      return NextResponse.json(
        { ok: false, error: `Missing field: ${k}` },
        { status: 400 }
      );
    }
  }

  const input: ConceptInput = {
    idea: body.idea ?? "",
    tokenName: body.tokenName ?? "KOKi",
    ticker: (body.ticker ?? "KOKI").toUpperCase(),
    chain: body.chain ?? "solana",
    theme: body.theme ?? "",
    audience: body.audience ?? "",
    launchStyle: body.launchStyle ?? "fair-launch",
    websiteUrl: body.websiteUrl ?? "",
    twitterUrl: body.twitterUrl ?? "",
    telegramUrl: body.telegramUrl ?? "",
    logoDataUrl: body.logoDataUrl ?? null,
  };

  const active = getActiveProvider();

  // Path A: no provider configured → mock
  if (!active) {
    const kit = generateMockLaunchKit(input);
    return NextResponse.json({
      ok: true,
      mock: true,
      provider: "mock",
      model: "koki-mock-generator",
      kit,
      note:
        "No LLM provider configured. Set XAI_API_KEY (recommended) to enable Grok.",
    });
  }

  // Path B: try real LLM, fall back to mock on any failure
  try {
    const messages = buildLaunchKitMessages(input);
    const llm = await callLLM({
      messages,
      responseFormat: "json",
      temperature: 0.7,
      maxTokens: 4096,
    });

    let kit;
    try {
      kit = parseLaunchKit(llm.content);
    } catch (parseErr) {
      // Parse failed → log details, return mock so the wizard keeps moving
      const reason =
        parseErr instanceof LaunchKitParseError
          ? parseErr.message
          : String(parseErr);
      return NextResponse.json({
        ok: true,
        mock: true,
        provider: "mock",
        model: "koki-mock-generator",
        fallbackReason: `LLM (${llm.provider}/${llm.model}) returned unparseable JSON: ${reason}`,
        kit: generateMockLaunchKit(input),
      });
    }

    return NextResponse.json({
      ok: true,
      mock: false,
      provider: llm.provider,
      model: llm.model,
      usage: llm.usage,
      kit,
    });
  } catch (err) {
    const reason =
      err instanceof LLMRouterError
        ? `${err.message} | attempts: ${JSON.stringify(err.attempts)}`
        : err instanceof Error
        ? err.message
        : String(err);
    return NextResponse.json({
      ok: true,
      mock: true,
      provider: "mock",
      model: "koki-mock-generator",
      fallbackReason: reason,
      kit: generateMockLaunchKit(input),
    });
  }
}
